### ISSUE TITLE
xfce panel indicators hover problem

### ISSUE THREAD

**Issue by waster** [lassekongo83/zuki-themes#59]
Hello,

I have gray background on hover indicators (xfce4-indicator-plugin) on then Xubuntu 16.04 LTS.
[Here](http://storage2.static.itmages.com/i/16/0422/h_1461317759_7771631_e4bb4409ae.png) is example.

How can it be fixed?

With regards, Andrey.

**Comment by lassekongo83** [comment]
Should be fixed in the latest commit. Just reload the panel or the theme once you have it.

**Comment by waster** [comment]
Installed theme with the latest commit, reloaded panel and theme, but gray backround color  is still exist while hovering. Although there is no more annoying little movements of indicators.

**Comment by lassekongo83** [comment]
Hmm. It works for me. Try logging out and in again.

**Comment by waster** [comment]
Already did...8)  [Here](http://storage6.static.itmages.com/i/16/0422/h_1461323910_7379989_b140f8172a.png) is what I see now.

Can be any overrides somewhere?

**Comment by waster** [comment]
BTW, it works with Zukitre

**Comment by lassekongo83** [comment]
There was a slight problem with the gtk3 applet thinking it could use a pixmap from the gtk2 theme. Should be fixed now.

**Comment by waster** [comment]
Great. It works now. Thanks.
